services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/ssl/certs/cert.pem
      - ./key.pem:/etc/ssl/certs/key.pem
  host-ui:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
      args:
        - SERVICE_DIR=host
    env_file:
      - .env.dev
    environment:
      - VITE_SERVICE_TYPE=ui
      - VITE_SERVICE_NAME=host
      - VITE_SERVICE_VERSION=v1
      - VITE_SERVICE_ID=host.ui
      - VITE_SERVICE_DB_SCHEMA=host

      - UI_DEPENDENCY_REMOTE=http://localhost/ui/v1/remote/remoteEntry.js
    volumes:
      - ./apps/host:/app/apps/host

  remote-ui:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
      args:
        - SERVICE_DIR=remote
    env_file:
      - .env.dev
    environment:
      - VITE_SERVICE_TYPE=ui
      - VITE_SERVICE_NAME=remote
      - VITE_SERVICE_VERSION=v1
      - VITE_SERVICE_ID=remote.ui
      - VITE_SERVICE_DB_SCHEMA=remote
    volumes:
      - ./apps/remote:/app/apps/remote

networks:
  shared-net:
    name: net
