FROM node:22-slim

ARG SERVICE_DIR

WORKDIR /app

RUN corepack enable

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml ./
COPY ./apps/${SERVICE_DIR}/package.json ./apps/${SERVICE_DIR}/package.json

RUN pnpm install --frozen-lockfile --filter ./apps/${SERVICE_DIR}...

WORKDIR /app/apps/${SERVICE_DIR}

ENV HMR_PORT=80

EXPOSE 2000

CMD [ "pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "2000" ]